// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZIyFWELgYj7OYlNSiPyJ5p5HuOtGytQ',
    appId: '1:94981251985:web:cc83b853d2baa3bff0f030',
    messagingSenderId: '94981251985',
    projectId: 'gwana-lojain-hamza',
    authDomain: 'gwana-lojain-hamza.firebaseapp.com',
    storageBucket: 'gwana-lojain-hamza.firebasestorage.app',
    measurementId: 'G-XHQB1SYZ29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIqUUsGBBxSIyzWVO3Pb6LFCnFY4xX4Ww',
    appId: '1:94981251985:android:acf23eb66f06aaf6f0f030',
    messagingSenderId: '94981251985',
    projectId: 'gwana-lojain-hamza',
    storageBucket: 'gwana-lojain-hamza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHHEsEprAPZpRE8Ad8U-AnC5b2VI2Eu2E',
    appId: '1:94981251985:ios:4962235202e9f39df0f030',
    messagingSenderId: '94981251985',
    projectId: 'gwana-lojain-hamza',
    storageBucket: 'gwana-lojain-hamza.firebasestorage.app',
    iosBundleId: 'com.example.gwana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHHEsEprAPZpRE8Ad8U-AnC5b2VI2Eu2E',
    appId: '1:94981251985:ios:4962235202e9f39df0f030',
    messagingSenderId: '94981251985',
    projectId: 'gwana-lojain-hamza',
    storageBucket: 'gwana-lojain-hamza.firebasestorage.app',
    iosBundleId: 'com.example.gwana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKZIyFWELgYj7OYlNSiPyJ5p5HuOtGytQ',
    appId: '1:94981251985:web:964e74920186472ef0f030',
    messagingSenderId: '94981251985',
    projectId: 'gwana-lojain-hamza',
    authDomain: 'gwana-lojain-hamza.firebaseapp.com',
    storageBucket: 'gwana-lojain-hamza.firebasestorage.app',
    measurementId: 'G-Z4VBSL1YJD',
  );
}
